### ISSUE TITLE
Project Requirements Checklist

### ISSUE THREAD

**Issue by wifelette** [wifelette/sinatra-cms-app-assessment-v-000#1]
Specs:
- [x] Use Sinatra to build the app
- [x] Use ActiveRecord for storing information in a database
- [x] Include more than one model class (e.g. User, Post, Category)
- [x] Include at least one has_many relationship on your User model (e.g. User has_many Posts)
- [x] Include at least one belongs_to relationship on another model (e.g. Post belongs_to User)
- [x] Include user accounts with unique login attribute (username or email)
- [x] Ensure that the belongs_to resource has routes for:
  - [x] Creating, 
  - [x] Reading, 
  - [x] Updating and 
  - [x] Destroying
- [x] Ensure that users can't modify content created by other users
- [x] Include user input validations
- [x] BONUS - not required - Display validation failures to user with error message (example form URL e.g. /posts/new)
- [x] Your README.md includes a short description, install instructions, a contributors guide and a link to the license for your code

Confirm
- [x] You have a large number of small Git commits
- [x] Your commit messages are meaningful
- [x] You made the changes in a commit that relate to the commit message
- [x] You don't include changes in a commit that aren't related to the commit message

**Comment by wifelette** [comment]
> Ensure that users can't modify content created by other users

It's not enough that they can't _navigate to_ the stuff directly via UI. If they type in the (easily predictable) URL they still need to not be able to.
